temp-schema:
  OSMSchema.xsd:
    file: OSMSchema.xsd
    source: https://gist.github.com/simon04/24ac9e9b1d0ce3c6655c1ffb2329ebc7
  osm-wiki-api-v06:
    file: osm-wiki-api-v06.dtd
    source: https://wiki.openstreetmap.org/wiki/API_v0.6/DTD
  osm-wiki-api-capabilities-v06:
    file: osm-wiki-api-capabilities-v06.xsd
    source: https://wiki.openstreetmap.org/wiki/API_v0.6/XSD
    note: |
      This xsd matches the description of the GET /api/capabilities api-call.
      C00002.xml

testdata:
  C00001:
    file: C00001.xml
    source: https://wiki.openstreetmap.org/wiki/OSM_XML
  C00002:
    file: C00002.xml
    source: https://wiki.openstreetmap.org/wiki/API_v0.6#Capabilities:_GET_.2Fapi.2Fcapabilities
  C0003:
    file: C0003.json
    source: https://wiki.openstreetmap.org/wiki/OSM_JSON
